# 🔢 NumPy Basics – Day 2 of Data Science Journey

**Author:** Vidhi Pandey  
**Date:** June 2025  
**Goal:** Learn NumPy arrays, indexing, vectorized operations, reshaping, broadcasting, and basic stats functions.


In [1]:
import numpy as np

In [2]:
# 1D Array
arr1 = np.array([1, 2, 3, 4])
print("1D Array:", arr1)

# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)


1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [3]:
print("Shape:", arr2.shape)
print("Data Type:", arr2.dtype)
print("Size:", arr2.size)
print("Dimensions:", arr2.ndim)

Shape: (2, 3)
Data Type: int64
Size: 6
Dimensions: 2


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Dot Product:", np.dot(a, b))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Dot Product: 32


In [5]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Element at (0,1):", arr[0, 1])
print("First row:", arr[0])
print("First column:", arr[:, 0])

Element at (0,1): 20
First row: [10 20 30]
First column: [10 40]


In [6]:
arr = np.arange(12)  # Creates array [0 to 11]
reshaped = arr.reshape(3, 4)
print("Reshaped:\n", reshaped)

flattened = reshaped.flatten()
print("Flattened:", flattened)

Reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [7]:
arr = np.array([[1, 2], [3, 4]])

print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())
print("Max:", arr.max())
print("Min:", arr.min())

Sum: 10
Mean: 2.5
Standard Deviation: 1.118033988749895
Max: 4
Min: 1


In [8]:
print("Random Integers:\n", np.random.randint(1, 10, (3, 3)))
print("Zeros:\n", np.zeros((2, 2)))
print("Ones:\n", np.ones((2, 2)))
print("Identity:\n", np.eye(3))

Random Integers:
 [[2 2 2]
 [8 5 2]
 [9 2 2]]
Zeros:
 [[0. 0.]
 [0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# Create a 5x5 array with values from 1 to 25
# Reshape it, and print:
# - Even numbers only
# - Sum of each row
# - Maximum in each column

# Hint:
# arr[arr % 2 == 0] gives even numbers

arr = np.arange(1,26)
reshaped=arr.reshape(5,5)
print("Reshaped:\n", reshaped)
print("Even Numbers in array : ",arr[arr%2==0])

for i in range(5):
    print(f"sum of {i+1} row is : ", reshaped[i].sum())
    print(f"Maximum number of {i+1} colimn is : ",reshaped[:,i].max())







Reshaped:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Even Numbers in array :  [ 2  4  6  8 10 12 14 16 18 20 22 24]
sum of 1 row is :  15
Maximum number of 1 colimn is :  21
sum of 2 row is :  40
Maximum number of 2 colimn is :  22
sum of 3 row is :  65
Maximum number of 3 colimn is :  23
sum of 4 row is :  90
Maximum number of 4 colimn is :  24
sum of 5 row is :  115
Maximum number of 5 colimn is :  25


In [1]:
# Vectorized operations
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# Vectorized addition
print("a + b =", a + b)

# Multiply each element by 2
print("a * 2 =", a * 2)

# Element-wise square
print("a squared =", a ** 2)

a + b = [11 22 33]
a * 2 = [2 4 6]
a squared = [1 4 9]


# Broadcasting array

In [2]:
# Broadcasting a scalar
a = np.array([1, 2, 3])
print("a + 5 =", a + 5)  # adds 5 to every element

# 2D and 1D example
A = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

print("A + b =\n", A + b)  # adds b to each row


a + 5 = [6 7 8]
A + b =
 [[11 22 33]
 [14 25 36]]


# Common statistical Functions

In [3]:
arr = np.array([5, 2, 9, 1, 7])

print("Array:", arr)
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Sum:", np.sum(arr))
print("Max:", np.max(arr), "at index", np.argmax(arr))
print("Min:", np.min(arr), "at index", np.argmin(arr))
print("75th Percentile:", np.percentile(arr, 75))
print("Median:", np.median(arr))

Array: [5 2 9 1 7]
Mean: 4.8
Standard Deviation: 2.9933259094191533
Variance: 8.96
Sum: 24
Max: 9 at index 2
Min: 1 at index 3
75th Percentile: 7.0
Median: 5.0


# useful numpy generators

In [4]:
print("Random integers (2x3):\n", np.random.randint(1, 100, (2, 3)))
print("Random floats:\n", np.random.rand(2, 2))  # Uniform [0,1)
print("Normal dist (mean=0, std=1):\n", np.random.randn(2, 2))

Random integers (2x3):
 [[16 54 31]
 [ 7 81 72]]
Random floats:
 [[0.61275224 0.32281305]
 [0.25577276 0.37810637]]
Normal dist (mean=0, std=1):
 [[-1.40243316  0.93773719]
 [-0.86203372 -0.25004326]]


In [5]:
# Generate an array of 1000 values from normal distribution
data = np.random.randn(1000)

# Print mean and standard deviation
print("Mean:", np.mean(data))
print("Standard Deviation:", np.std(data))


Mean: 0.004587700757756518
Standard Deviation: 0.9897827858470163
